<a href="https://colab.research.google.com/github/0223yunhui/AIpython/blob/main/250509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

type(a)

[1 2 3]


numpy.ndarray

In [ ]:
#문제 1: 다음 조건에 맞는 배열을 생성하고 출력하세요.
#1차원 배열, 5개의 요소, 0으로 초기화된 배열

import numpy as np

arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
#문제 2: 1부터 10까지의 숫자 중 짝수만 포함하는 배열을 생성하세요.

import numpy as np

arr=np.arange(2, 11, 2)
print(arr)

[1 3 5 7 9]


In [ ]:
#문제 3: [2, 4, 6] 배열과 [10, 20, 30] 배열을 각각 생성하고, 곱셈 연산을 수행한 결과를 출력하세요.

import numpy as np

arr1=np.arange(2, 7, 2)
arr2=np.arange(10, 31, 10)
print(arr1*arr2)

[ 20  80 180]


In [ ]:
a = np.array([2, 4, 6])
b = np.array([10, 20, 30])

result = a * b
print(result)

[ 20  80 180]


In [ ]:
#문제 4: 위 배열에서 20보다 큰 요소만 필터링해서 출력하세요.

arr1=np.arange(2, 7, 2)
arr2=np.arange(10, 31, 10)

filtered = result[result > 20]
print(filtered)

[ 80 180]


In [30]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}
df = pd.DataFrame(data)
df.to_csv('output_students.csv', index=False)

In [31]:
df = pd.read_csv('archive.zip')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [32]:
df = pd.read_csv('archive.zip')
print(df.describe())

       Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

         zero  zero.1  zero.2  zero.3  zero.4  ...  zero.12  zero.13  zero.14  \
count  1309.0  1309.0  1309.0  1309.0  1309.0  ...   1309.0   1309.0   1309.0   
mean      0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
std       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
min      

In [36]:
df[df['Age'] > 25]

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
5               6  28.0    8.4583    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
5          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
5          1.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[866 rows x 28 columns]

In [44]:
df.loc[0, 'Age'] = 28
df.head(5)

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  28.0   7.2500    0      1     0       0       0       0   
1            2  26.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  26.0   8.0500    0      0     0       0       0       0   

   zero.4  ...  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  zero.17  \
0       0  ...        0        0       3        0        0       2.0        0   
1       0  ...        0        0       1        0        0       0.0        0   
2       0  ...        0        0       3        0        0       2.0        0   
3       0  ...        0        0       1        0        0       2.0        0   
4       0  ...        0        0       3        0        0       2.0        0   

   zero.18  2urvived    나이  
0        0         0  26.0  
1        0         1   NaN  
2        0         1   NaN  
3        0         1   NaN  
4        0         0   NaN  

[5 rows x 29 columns]

In [46]:
result = df.groupby('Sex')['Age'].mean()
print(result)

Sex
0    30.01433
1    28.54633
Name: Age, dtype: float64
